Applications of Accelerators WS2023
Ex01

Q11- Write a function in Python code that multiples 2 (two) 3x3 Matrices (ndarray) and returns the result.
Call this function using two randomly generated 3 by 3 matrices and print the results.

In [18]:
import numpy as np

In [19]:
# function
def multiply_matrices(matrix1, matrix2):
        return np.dot(matrix1, matrix2)

In [20]:
matrix_a = np.random.rand(3,3)

In [21]:
matrix_b = np.random.rand(3,3)

In [22]:
#call the function
result = multiply_matrices(matrix_a, matrix_b)

In [23]:
#print random matrix A
print(matrix_a)

[[0.62144098 0.60647379 0.56032601]
 [0.70101824 0.91463264 0.33497418]
 [0.76763721 0.08263008 0.93511464]]


In [24]:
#print random matrix B
print(matrix_b)

[[0.98555297 0.86584216 0.75549308]
 [0.1708739  0.85736387 0.59649103]
 [0.17736196 0.10280696 0.32291412]]


In [25]:
#prent the result
print(result)

[[0.81547407 1.11564394 1.01218772]
 [0.90658913 1.42558181 1.18335249]
 [0.93652022 0.831633   0.93119442]]
