Applications of Accelerators WS2023
Ex01

Q11- Write a function in Python code that multiples 2 (two) 3x3 Matrices (ndarray) and returns the result.
Call this function using two randomly generated 3 by 3 matrices and print the results.

In [30]:
import numpy as np

In [31]:
# function
def multiply_matrices(matrix1, matrix2):
    if matrix1.shape == (3, 3) and matrix2.shape == (3, 3):
        return np.dot(matrix1, matrix2)

In [32]:
matrix_a = np.random.rand(3, 3)

In [33]:
matrix_b = np.random.rand(3, 3)

In [34]:
#call the function
result = multiply_matrices(matrix_a, matrix_b)

In [35]:
#print random matrix A
print(matrix_a)

[[0.47658286 0.9623662  0.65268985]
 [0.15665658 0.27795207 0.66270688]
 [0.57908908 0.63378278 0.10810804]]


In [36]:
#print random matrix B
print(matrix_b)

[[0.72899674 0.53817453 0.22856637]
 [0.74305531 0.18036246 0.72414756]
 [0.81345456 0.6741279  0.65303137]]


In [37]:
#prent the result
print(result)

[[1.5934522  0.87005593 1.2320529 ]
 [0.85981783 0.5811899  0.66985312]
 [0.9810307  0.49884026 0.66191049]]
